#                  _       _                              _                    
#  _   _ _ __   __| | __ _| |_ ___       _ __   __ _  ___| | ____ _  __ _  ___ 
# | | | | '_ \ / _` |/ _` | __/ _ \_____| '_ \ / _` |/ __| |/ / _` |/ _` |/ _ \
# | |_| | |_) | (_| | (_| | ||  __/_____| |_) | (_| | (__|   < (_| | (_| |  __/
#  \__,_| .__/ \__,_|\__,_|\__\___|     | .__/ \__,_|\___|_|\_\__,_|\__, |\___|
#       |_|                             |_|                         |___/      
- hosts: all
  become: true
  become_user: root
  remote_user: root
  tasks:
    - name: update-package | All the packages should be updated
      when: ansible_os_family == "RedHat"
      raw: yum -y update

    - name: update-package | Debian | All the packages should be updated
      when: ansible_os_family == "Debian"
      raw: apt -y update

