#  _               _                            _                          
# | |__   ___  ___| |_      ___ _ __   ___  ___(_)_ __ ___   ___ _ __  ___ 
# | '_ \ / _ \/ __| __|____/ __| '_ \ / _ \/ __| | '_ ` _ \ / _ \ '_ \/ __|
# | | | | (_) \__ \ ||_____\__ \ |_) |  __/ (__| | | | | | |  __/ | | \__ \
# |_| |_|\___/|___/\__|    |___/ .__/ \___|\___|_|_| |_| |_|\___|_| |_|___/
#                              |_|                                         
- hosts: all
  become: true
  become_user: root
  remote_user: deploy
  vars:
    prefix: "cx-"
    suffix: "-{{ ansible_date_time.date }}-{{ ansible_date_time.hour }}{{ ansible_date_time.minute }}"
    destination: "~/"
    servicelist: ["postfix", "dovecot"]
    journalopts: "-r -p3 -S today --no-pager -n 100"
  tasks:
    - name: host-specimens | uptime command should be executed
      shell: >
        uptime > ./{{ prefix }}uptime{{ suffix }}
      args:
        chdir:   "{{ destination }}"
        creates: "./{{ prefix }}uptime{{ suffix }}"

    - name: host-specimens | ps command should be executed
      shell: >
        ps auxwwf > ./{{ prefix }}ps{{ suffix }}
      args:
        chdir:   "{{ destination }}"
        creates: "./{{ prefix }}ps{{ suffix }}"

    - name: host-specimens | top command should be executed
      shell: >
        top -bc -n 1 > ./{{ prefix }}top{{ suffix }}
      args:
        chdir:   "{{ destination }}"
        creates: "./{{ prefix }}top{{ suffix }}"

    - name: host-specimens | free command should be executed
      shell: >
        free -m > ./{{ prefix }}free{{ suffix }}
      args:
        chdir:   "{{ destination }}"
        creates: "./{{ prefix }}free{{ suffix }}"

    - name: host-specimens | df command should be executed
      shell: >
        df -h > ./{{ prefix }}df{{ suffix }}
      args:
        chdir:   "{{ destination }}"
        creates: "./{{ prefix }}df{{ suffix }}"

    - name: host-specimens | netstat -nat command should be executed
      shell: >
        netstat -nat > ./{{ prefix }}netstat-nat{{ suffix }}
      args:
        chdir:   "{{ destination }}"
        creates: "./{{ prefix }}netstat-nat{{ suffix }}"

    - name: host-specimens | netstat -nar command should be executed
      shell: >
        netstat -nar > ./{{ prefix }}netstat-nar{{ suffix }}
      args:
        chdir:   "{{ destination }}"
        creates: "./{{ prefix }}netstat-nar{{ suffix }}"

    - name: host-specimens | ls /tmp command should be executed
      shell: >
        ls -laF /tmp > ./{{ prefix }}ls-tmp{{ suffix }}
      args:
        chdir:   "{{ destination }}"
        creates: "./{{ prefix }}ls-tmp{{ suffix }}"

    - name: host-specimens | journalctl -k command should be executed
      shell: >
        journalctl {{ journalopts }} -k > ./{{ prefix }}journalctl-kernel{{ suffix }}
      args:
        chdir:   "{{ destination }}"
        creates: "./{{ prefix }}journalctl-kernel{{ suffix }}"

    - name: host-specimens | systemctl command should be executed
      shell: >
        journalctl {{ journalopts }} -u {{ item }} > ./{{ prefix }}journalctl-{{ item }}{{ suffix }}
      args:
        chdir:   "{{ destination }}"
        creates: "./{{ prefix }}journalctl-{{ item }}{{ suffix }}"
      with_items: "{{ servicelist }}"

    - name: host-specimens | systemctl command should be executed
      shell: >
        systemctl status {{ item }} > ./{{ prefix }}systemctl-{{ item }}{{ suffix }}
      args:
        chdir:   "{{ destination }}"
        creates: "./{{ prefix }}systemctl-{{ item }}{{ suffix }}"
      with_items: "{{ servicelist }}"

