#!/bin/sh
#
PATH='/usr/local/bin:/usr/bin:/bin'
LANG='C'
LC_CTYPE='C'

if [ "`uname -s`" = "Linux" ]; then
    /usr/sbin/setenforce 0
    sed -i "s/\(^SELINUX=\).*/\1disabled/" /etc/selinux/config
fi

